/* ===== Question banks, mock tests, flashcards ===== */

const TOPIC_QUIZZES = [
{
  id: "q-types", topicId: "types-of-business", icon: "🏪", title: "Types of Business",
  blurb: "Profit math, non-profits, service areas, business size, goods vs services.",
  questions: [
    { q: "The money a business makes by selling goods or services is called…",
      choices: ["Profit", "Revenue", "Expenses", "Cost"], a: 1,
      explain: "Revenue = money made from SELLING. Profit is what's left after expenses and costs are paid." },
    { q: "Profit (or loss) is calculated as…",
      choices: ["Revenue + Expenses + Costs", "Revenue − Expenses − Costs", "Expenses − Revenue", "Revenue × Costs"], a: 1,
      explain: "Profit (or loss) = Revenue − Expenses − Costs." },
    { q: "You earn $200 selling backpacks. Materials cost $100 and renting the heat press costs $40. Your result is…",
      choices: ["$240 profit", "$160 profit", "$60 profit", "$60 loss"], a: 2,
      explain: "200 − 100 − 40 = $60 profit." },
    { q: "Which statement about NON-PROFIT organizations is true?",
      choices: ["They cannot earn any revenue", "Any profit must be reinvested into the organization's mission", "They distribute profits to directors as dividends", "They always sell goods, never services"], a: 1,
      explain: "Non-profits CAN earn revenue (fees, sales), but profits must be reinvested to further the mission — never paid out as personal gain." },
    { q: "Which of these is a non-profit organization?",
      choices: ["Apple", "Tim Hortons", "Amnesty International", "A McDonald's franchise"], a: 2,
      explain: "Amnesty International (like charities) serves a social/human-rights purpose. The others operate to make a profit." },
    { q: "A company that operates in multiple countries is classified by service area as…",
      choices: ["Local", "Regional", "National", "Global"], a: 3,
      explain: "Global = operates within multiple countries. National = within one country." },
    { q: "A business with 85 employees is classified as…",
      choices: ["Small (1–99)", "Medium (100–500)", "Large (500+)", "Regional"], a: 0,
      explain: "Small = 1–99 employees, Medium = 100–500, Large = more than 500." },
    { q: "In Canada, small and medium businesses provide jobs for about ___ of the workforce.",
      choices: ["20%", "40%", "60%", "80%"], a: 2,
      explain: "About 60% of the Canadian workforce — there are over 1 million small-to-medium businesses in Canada." },
    { q: "A haircut, a plumbing repair, and tax advice are all examples of…",
      choices: ["Goods", "Services", "Capital resources", "Non-profits"], a: 1,
      explain: "A service is assistance provided. Goods are items you can see or touch." },
    { q: "When a business makes a profit, what can it do with the money?",
      choices: ["Reinvest it for expansion", "Provide improved goods and services", "Give owners funds for personal needs or wants", "All of the above"], a: 3,
      explain: "All three — reinvest, improve, or personal funds for the owner(s)." }
  ]
},
{
  id: "q-maslow", topicId: "wants-needs-maslow", icon: "🧠", title: "Wants, Needs & Maslow",
  blurb: "Needs vs wants, the 5 hierarchy levels, obsolete products, trends vs fads.",
  questions: [
    { q: "Which of the following is a NEED (not a want)?",
      choices: ["Concert tickets", "Designer jeans", "Basic groceries", "A movie streaming subscription"], a: 2,
      explain: "Needs are required to live, stay healthy and work — like basic groceries, clean water, shelter, medication." },
    { q: "Eating at restaurants and going to concerts are examples of…",
      choices: ["Needs", "Wants", "Natural resources", "Consumer rights"], a: 1,
      explain: "Wants add comfort and pleasure but aren't necessary for survival." },
    { q: "Maslow's hierarchy of needs was created by…",
      choices: ["Abraham Maslow, a social psychologist", "Peter Drucker, a management expert", "Adam Smith, an economist", "Bill Gates"], a: 0,
      explain: "Abraham Maslow studied the broad spectrum of human psychological needs." },
    { q: "Which need comes DIRECTLY ABOVE safety needs in Maslow's hierarchy?",
      choices: ["Physiological", "Belongingness", "Ego", "Self-actualization"], a: 1,
      explain: "Order: 1. Physiological → 2. Safety → 3. Belongingness → 4. Ego → 5. Self-actualization." },
    { q: "Water, sleep, and food belong to which Maslow level?",
      choices: ["Safety", "Physiological", "Ego", "Belongingness"], a: 1,
      explain: "Physiological needs = water, sleep, food — the base of the pyramid." },
    { q: "'Striving to realize your full potential' describes…",
      choices: ["Ego needs", "Safety needs", "Self-actualization", "Belongingness"], a: 2,
      explain: "Self-actualization is the top level — realizing your full potential." },
    { q: "A home security system satisfies a SAFETY need, but its ad shows a happy family. The advertiser is appealing to…",
      choices: ["Physiological needs", "Belongingness needs (love of family)", "Self-actualization", "The same level"], a: 1,
      explain: "A product might meet a need on one level, but the advertisement often uses a different level to motivate the consumer." },
    { q: "Online shopping and AI in business, which have lasted for years, are examples of…",
      choices: ["Fads", "Trends", "Obsolete products", "Surpluses"], a: 1,
      explain: "A trend is a general direction in society that lasts a LONG time (years). A fad lasts less than a year." },
    { q: "Fidget spinners were hugely popular for a few months, then disappeared. They were a…",
      choices: ["Trend", "Fad", "Need", "Capital resource"], a: 1,
      explain: "Fads are temporary, short-term changes — likely less than a year (fidget spinners, squishies)." },
    { q: "A product that is no longer a want or need — like tape players or VCRs — is called…",
      choices: ["Obsolete", "A fad", "A surplus", "Depreciated"], a: 0,
      explain: "Obsolete: when consumers stop buying, producers stop making." },
    { q: "Why did Wheaties Dunk-A-Balls cereal fail?",
      choices: ["It tasted bad", "Parents disliked that it encouraged kids to play with their food", "It was too expensive", "A competitor copied it"], a: 1,
      explain: "The makers misunderstood their target market — the parents buying the cereal — and the product was pulled." }
  ]
},
{
  id: "q-ownership", topicId: "forms-of-ownership", icon: "🏢", title: "Forms of Ownership",
  blurb: "The 5 forms, liability, shareholders, dividends, boards, corporation types, franchises.",
  questions: [
    { q: "A business owned by ONE person who is responsible for all its losses is a…",
      choices: ["Partnership", "Sole proprietorship", "Corporation", "Co-operative"], a: 1,
      explain: "Sole proprietorship: one owner = the proprietor, who keeps all profit but carries all losses (unlimited liability)." },
    { q: "'Unlimited liability' means…",
      choices: ["The business can borrow unlimited money", "The owner is personally responsible for all business losses", "The company has unlimited shareholders", "Liability is shared between partners"], a: 1,
      explain: "Owner and business are the same legal entity — personal assets can be used to cover business debts." },
    { q: "Sole proprietors usually get their start-up funds from…",
      choices: ["Selling shares on the stock market", "Savings, friends, family, or a bank loan", "Government grants only", "Dividends"], a: 1,
      explain: "Sole proprietors can't sell public shares — funds come from personal sources and loans." },
    { q: "In a GENERAL partnership…",
      choices: ["Only one partner runs the business", "Partners share gains, losses and unlimited liability", "Partners have limited liability", "The business is owned by shareholders"], a: 1,
      explain: "General partnership (most common): 'what's yours is mine and what's mine is yours' — shared gains, losses, unlimited liability." },
    { q: "In a limited partnership, limited partners…",
      choices: ["Run the business daily", "Are only responsible for the funds they invested", "Have unlimited liability", "Must be family members"], a: 1,
      explain: "The general partner runs the business (unlimited liability); limited partners only risk the money they put in — limited liability." },
    { q: "The terms of a partnership are recorded in the…",
      choices: ["Annual report", "Partnership agreement", "Prospectus", "Charter of rights"], a: 1,
      explain: "The partnership agreement records responsibilities, ownership splits, profit shares — and what happens if a partner leaves." },
    { q: "Which is an ADVANTAGE of a partnership?",
      choices: ["Profit sharing", "Combined skills and expertise", "Unlimited liability", "Partners always agree"], a: 1,
      explain: "Combined skills & expertise (also: easy to start, shared financial burden, profits taxed as personal income). Profit sharing and unlimited liability are DISadvantages." },
    { q: "Why doesn't the owner of a corporation get personally sued when the corporation is sued?",
      choices: ["Corporations never get sued", "The owner and business are separate legal entities", "Owners buy special insurance", "The board of directors takes the blame"], a: 1,
      explain: "A corporation has legal status distinct from the people who own or work for it — the owner is protected." },
    { q: "Individuals who hold shares in a corporation are called ___, and regular payments of profit to them are called ___.",
      choices: ["directors; salaries", "shareholders; dividends", "proprietors; wages", "members; dues"], a: 1,
      explain: "Shareholders become owners of the business; dividends are regular payments of profit to investors who own the stock." },
    { q: "The board of directors of a public corporation is elected by…",
      choices: ["The CEO", "The employees", "The shareholders", "The government"], a: 2,
      explain: "Shareholders elect the board, which sets strategy, oversees management, and can even fire the CEO." },
    { q: "Which is a PRIVATE corporation?",
      choices: ["Apple", "IKEA", "Canada Post", "Toronto Hydro"], a: 1,
      explain: "Private corporations are owned by a small group and their shares aren't publicly traded (IKEA, Lego). Apple is public; Canada Post is a Crown corporation; Toronto Hydro is municipal." },
    { q: "Canada Post and CBC are examples of…",
      choices: ["Public corporations", "Crown corporations", "Municipal corporations", "Co-operatives"], a: 1,
      explain: "Crown corporations are government-owned, operate commercially, and provide public service while keeping financial independence." },
    { q: "A co-operative operates democratically, which means…",
      choices: ["The founder makes all decisions", "One member = one vote", "Shareholders vote by number of shares", "The government votes"], a: 1,
      explain: "Co-ops are owned by members who share profits and decision-making — one member, one vote, focused on members' needs not max profit." },
    { q: "To open a franchise, the franchisee pays the franchisor…",
      choices: ["Nothing — it's free", "An initial fee plus a % of sales as an ongoing fee", "Only yearly taxes", "A share of the company"], a: 1,
      explain: "In exchange the franchisee gets the brand, products/recipes, marketing, and a proven business system." },
    { q: "Which is a challenge a franchisee may face?",
      choices: ["Unlimited liability for company debts", "Strict rules and limited freedom to make changes", "Must invent their own menu and logo", "No support from the brand"], a: 1,
      explain: "Franchisees face limited freedom, strict consistency rules, competition with other franchises, brand-reputation risk, and high investment fees." }
  ]
},
{
  id: "q-ethics", topicId: "ethics-csr", icon: "🌍", title: "Business Ethics & CSR",
  blurb: "Ethics vocabulary, fraud, insider trading, whistleblowing, the 5 CSR principles.",
  questions: [
    { q: "Ethics are…",
      choices: ["Laws passed by government", "Rules that help us tell right from wrong", "Company profits", "Accounting documents"], a: 1,
      explain: "Ethics help us tell the difference between right and wrong and encourage us to do the right thing." },
    { q: "'What we think is important' describes our ___, while rules we use to decide good from bad are our ___.",
      choices: ["morals; values", "values; morals", "ethics; profits", "duties; rights"], a: 1,
      explain: "Values = what we think is important (e.g., respect). Morals = rules for good/bad (e.g., stealing is bad)." },
    { q: "Fair trade means…",
      choices: ["Selling everything at half price", "Ensuring basic labour rights of workers in other countries are respected", "Trading only within Canada", "Bartering goods instead of paying"], a: 1,
      explain: "Fair trade treats producers and workers fairly while still allowing businesses to make a profit." },
    { q: "An employee who informs officials or the public about an illegal or ethical violation is…",
      choices: ["An auditor", "A whistleblower", "A forensic accountant", "A shareholder"], a: 1,
      explain: "Whistle-blowing — named after a referee's whistle signalling foul play." },
    { q: "Creating false accounts and redirecting money into them for personal gain is…",
      choices: ["Insider trading", "Embezzlement", "A pyramid scheme", "Mail fraud"], a: 1,
      explain: "Embezzlement is a type of accounting fraud." },
    { q: "External accountants who check and report on the validity of financial records are…",
      choices: ["Auditors", "Directors", "Brokers", "Underwriters"], a: 0,
      explain: "Auditors check the books from outside the company; forensic accountants examine legal and financial documents." },
    { q: "Buying or selling shares based on confidential information is…",
      choices: ["Insider trading — illegal", "Smart investing — legal", "Dividend reinvesting", "Franchising"], a: 0,
      explain: "Insider trading is illegal. Punishments: fines up to $1 million, giving up all profits, up to 2 years in prison, and a trading ban." },
    { q: "Tricking consumers into buying things they don't need, or that don't work as promised, is…",
      choices: ["Bank fraud", "Consumer fraud", "Insurance fraud", "Telemarketer fraud"], a: 1,
      explain: "Consumer fraud. (Bank fraud = loans to fake businesses; insurance fraud = false claims; pyramid schemes = recruiting ever-more 'investors'.)" },
    { q: "Which is NOT one of the 5 CSR principles from class?",
      choices: ["Protecting the environment", "Truthful advertising", "Maximizing shareholder dividends", "Donating to charity"], a: 2,
      explain: "The 5 principles: safe/healthy workplace · fair labour policies · protecting the environment · truthful advertising (avoiding price discrimination) · donating to charity." },
    { q: "IKEA's 'Buy Back' program (customers return used furniture for resale) is an example of which CSR principle?",
      choices: ["Fair labour policies", "Protecting the environment", "Truthful advertising", "Safe work environment"], a: 1,
      explain: "It encourages recycling and keeps furniture out of landfills — protecting the environment (IKEA aims to be fully circular by 2030)." },
    { q: "An employer's obligation to ensure accessibility for all employees is called…",
      choices: ["The glass ceiling", "Duty to accommodate", "Whistle-blowing", "Insider trading"], a: 1,
      explain: "Duty to accommodate. The glass ceiling is the invisible barrier blocking women/minorities from top jobs." },
    { q: "A for-profit business that meets high standards of verified social and environmental performance, regulated by B Lab, is a…",
      choices: ["Crown corporation", "B Corporation", "Franchise", "Co-operative"], a: 1,
      explain: "B Corporations balance profit and purpose — verified performance, transparency, and legal accountability, regulated by B Lab." }
  ]
},
{
  id: "q-econ", topicId: "intro-economics", icon: "📈", title: "Intro to Economics",
  blurb: "Scarcity, economic systems, opportunity cost, resources, interdependence.",
  questions: [
    { q: "Economics is the study of…",
      choices: ["How to get rich", "Human decisions in using limited resources to satisfy unlimited needs and wants", "Only money and banks", "Government taxes"], a: 1,
      explain: "Limited resources, unlimited wants — economics studies the decisions in between." },
    { q: "'There are limited resources to produce limited goods, but human wants are unlimited' defines…",
      choices: ["Equilibrium", "Scarcity", "Surplus", "Interdependence"], a: 1,
      explain: "Scarcity forces us to make choices about how to use limited resources." },
    { q: "The three questions every economic system must answer are…",
      choices: ["Why? When? Where?", "WHAT to produce, HOW to produce it, and for WHOM", "Buy? Sell? Trade?", "Who? What? When?"], a: 1,
      explain: "What, how, and for whom — selection, production, distribution, and consumption of goods and services." },
    { q: "In a COMMAND economy…",
      choices: ["Prices are set by supply and demand", "The government owns resources, makes all decisions, and sets prices", "Businesses and government share decisions", "There are no goods produced"], a: 1,
      explain: "Command economy: government controls everything — limited consumer choice, standardized goods (e.g., North Korea, Cuba)." },
    { q: "In a MARKET economy, prices are determined by…",
      choices: ["The government", "Supply and demand", "Tradition", "The United Nations"], a: 1,
      explain: "Individuals and businesses decide based on supply and demand; distribution follows purchasing power (e.g., USA, Taiwan, New Zealand)." },
    { q: "Canada, the UK, and France are examples of…",
      choices: ["Command economies", "Pure market economies", "Mixed economies", "Traditional economies"], a: 2,
      explain: "Mixed economies: government and business share decision-making; most prices are market-driven but government regulates and ensures essential services. Most countries today are mixed." },
    { q: "You have $50 and choose gaming accessories over a dinner out, new clothes, or a concert. The concert experience you gave up is your…",
      choices: ["Revenue", "Expense", "Opportunity cost", "Surplus"], a: 2,
      explain: "Opportunity cost = the value of what you could have received but passed up when choosing another option." },
    { q: "Oil, trees, fish, and oxygen are examples of…",
      choices: ["Capital resources", "Human resources", "Natural resources", "Consumer goods"], a: 2,
      explain: "Natural resources come from the earth, water, and air — and most are non-renewable or slow to replenish." },
    { q: "Teachers, nurses, and factory workers are examples of…",
      choices: ["Natural resources", "Human resources (labour)", "Capital resources", "Entrepreneurs only"], a: 1,
      explain: "Human resources are the people who work to create goods and services." },
    { q: "Which is a CAPITAL resource?",
      choices: ["Iron ore", "A factory's machinery — and money", "A nurse", "Sunlight"], a: 1,
      explain: "Capital resources are human-made: buildings, machinery, tools, vehicles, factories. Money is also a capital resource." },
    { q: "When each business focuses on what it does best to be more efficient, it's called…",
      choices: ["Specialization", "Diversification", "Equilibrium", "Classification"], a: 0,
      explain: "Specialization leads to interdependence: the phone maker relies on companies specializing in chips, screens, and batteries." },
    { q: "A fast-food restaurant buying beef from a wholesaler, grills from an equipment company, and hiring cooks through an agency shows…",
      choices: ["A command economy", "A network of interdependence", "Unlimited liability", "A fad"], a: 1,
      explain: "Businesses rely on other businesses' goods and services (natural, capital, and human resources) to satisfy consumer needs." }
  ]
},
{
  id: "q-sd", topicId: "supply-demand", icon: "⚖️", title: "Supply & Demand",
  blurb: "The two laws, equilibrium, surplus, shortage.",
  questions: [
    { q: "Demand is…",
      choices: ["What producers offer for sale", "The quantity buyers are willing and able to buy at possible prices", "The price set by government", "Money left after expenses"], a: 1,
      explain: "Demand is from the BUYER's side, over a period of time, at all possible prices." },
    { q: "The LAW OF DEMAND says: the higher the price of a product…",
      choices: ["The more consumers will demand", "The less consumers will demand", "The more producers will supply", "The higher wages rise"], a: 1,
      explain: "Price ↑ → demand ↓. (Supply works the opposite way: price ↑ → supply ↑.)" },
    { q: "The LAW OF SUPPLY says: the higher the price of a product…",
      choices: ["The more producers will supply", "The less producers will supply", "The less consumers demand", "The more consumers buy"], a: 0,
      explain: "Higher prices make production more worthwhile, so producers offer more for sale." },
    { q: "Equilibrium is the price at which…",
      choices: ["Supply is greater than demand", "Demand is greater than supply", "Market supply equals market demand", "The government sets prices"], a: 2,
      explain: "At the equilibrium (market-clearing) price, buyers can buy all they want and sellers can sell all they want." },
    { q: "A store has too many winter coats in spring. This is a…",
      choices: ["Shortage", "Surplus", "Equilibrium", "Fad"], a: 1,
      explain: "Surplus = too much supply. Sellers lower prices to attract buyers, pushing the market back toward equilibrium." },
    { q: "A concert has more people wanting tickets than tickets available. This is a…",
      choices: ["Surplus", "Shortage", "Equilibrium", "Loss"], a: 1,
      explain: "Shortage = too much demand. Prices may rise and some buyers miss out — pushing toward equilibrium." },
    { q: "What usually happens to price during a SURPLUS?",
      choices: ["Prices rise", "Prices fall as sellers try to attract buyers", "Prices stay fixed", "Government bans sales"], a: 1,
      explain: "Sellers may lower prices to attract buyers — moving the market toward equilibrium." },
    { q: "In the Coffee Shop Game, 'running out of supplies on a busy day' shows why ___ management matters.",
      choices: ["Staff", "Inventory", "Marketing", "Tax"], a: 1,
      explain: "The game teaches producing the right supply to meet demand, factors affecting supply/demand, and inventory management." }
  ]
}
];

/* ===== Flashcards ===== */
const FLASHCARD_DECKS = [
{ id: "fc-types", icon: "🏪", title: "Types of Business", cards: [
  { f: "Revenue", b: "The money made by selling goods or services." },
  { f: "Expenses", b: "Payments involved in running a business and assets 'used up' operating it (e.g., day-rental of equipment)." },
  { f: "Cost", b: "The money required to produce or provide the goods and services (e.g., materials)." },
  { f: "Profit", b: "Income left after all costs and expenses are paid. Profit = Revenue − Expenses − Costs." },
  { f: "Non-profit organization", b: "Serves a social, charitable, or community purpose; any profit is reinvested into the mission, not distributed. E.g., charities, Amnesty International." },
  { f: "For-profit business", b: "Goal is to make a profit by supplying goods/services that meet consumer demand." },
  { f: "Service area classes", b: "Local (town/neighbourhood) → Regional (city/part of country) → National (one country) → Global (multiple countries)." },
  { f: "Business sizes", b: "Small = 1–99 employees · Medium = 100–500 · Large = 500+. Most Canadian businesses are small-medium (60% of the workforce; 1M+ businesses)." },
  { f: "Good vs Service", b: "Good = item you can see or touch (backpack, phone). Service = assistance provided (haircut, plumbing)." }
]},
{ id: "fc-maslow", icon: "🧠", title: "Wants, Needs & Maslow", cards: [
  { f: "Need", b: "Necessary for living our current lifestyles — required to live, stay healthy, work (groceries, water, rent, medication)." },
  { f: "Want", b: "Not necessary for survival, but adds comfort and pleasure (restaurants, designer clothes, concerts)." },
  { f: "Maslow Level 1 — Physiological", b: "Water, sleep, food. The base of the pyramid." },
  { f: "Maslow Level 2 — Safety", b: "Shelter, security, protection (e.g., home security system)." },
  { f: "Maslow Level 3 — Belongingness", b: "Love, friendship, acceptance." },
  { f: "Maslow Level 4 — Ego", b: "Self-esteem, achievement, uniqueness, independence." },
  { f: "Maslow Level 5 — Self-actualization", b: "Striving to realize your full potential. The top of the pyramid." },
  { f: "Trend", b: "A general direction or change in society that lasts a LONG time (years): online shopping, AI in business." },
  { f: "Fad", b: "A temporary, short-term change — likely less than a year: fidget spinners, squishies." },
  { f: "Obsolete product", b: "No longer a want or need; consumers stop buying so producers stop making. E.g., tape players, VCRs." }
]},
{ id: "fc-ownership", icon: "🏢", title: "Forms of Ownership", cards: [
  { f: "The 5 forms of ownership", b: "Sole Proprietorship · Partnership · Corporation · Co-operative · Franchise." },
  { f: "Sole Proprietorship", b: "Owned by 1 person (the proprietor). Keeps all profit, responsible for all losses. Funds from savings/friends/family/bank loan. E.g., plumber, electrician." },
  { f: "Unlimited liability", b: "Owner and business are the same legal entity — the owner is personally responsible for all business losses." },
  { f: "Partnership", b: "Two or more individuals share costs and responsibilities; terms recorded in the partnership agreement." },
  { f: "General vs Limited partnership", b: "General: all partners share gains, losses, unlimited liability. Limited: general partner runs it (unlimited); limited partners only risk invested funds (limited liability)." },
  { f: "Partnership pros & cons", b: "Pros: easy to start, shared burden, combined skills, profits taxed as personal income. Cons: profit sharing, unlimited liability (general), conflicts, hard if a partner leaves." },
  { f: "Corporation", b: "Legal status DISTINCT from the people who work for it — owner is separate from the business. Can be small (one person) or multinational." },
  { f: "Shareholders", b: "Individuals who hold shares (portions of ownership) — they become owners of the business and have limited liability." },
  { f: "Dividends", b: "Regular payments of profit made to investors who own a company's stock." },
  { f: "Board of Directors", b: "Governing body elected by shareholders: sets strategy, oversees management, hires/evaluates/fires the CEO, ensures legal & ethical conduct." },
  { f: "4 types of corporations", b: "Private (small group, not traded — IKEA, Lego) · Public (shares on stock markets — Apple, Tesla) · Crown (gov-owned — Canada Post, CBC) · Municipal (city-created — Toronto Hydro, TTC)." },
  { f: "Co-operative", b: "Owned by members/workers who use it; motivated by SERVICE not profit; democratic — one member = one vote; profits and decisions shared." },
  { f: "Why co-ops matter", b: "① Community oriented (profits reinvested) ② Ethical practices (sustainability, fair wages) ③ Democracy (workers control their workplace)." },
  { f: "Franchisor vs Franchisee", b: "Franchisor owns the name/products/system (Cocos HQ). Franchisee pays initial fee + % of sales to open a location using the brand, products, marketing." },
  { f: "Franchisee challenges", b: "Limited freedom · strict consistency rules · competition with other franchises · brand reputation risk · high investment fees." }
]},
{ id: "fc-ethics", icon: "🌍", title: "Ethics & CSR", cards: [
  { f: "Ethics", b: "Rules that help us tell right from wrong; they encourage us to do the right thing." },
  { f: "Values vs Morals", b: "Values = what we think is important (respect). Morals = rules for deciding good/bad (stealing is bad)." },
  { f: "Fair trade", b: "Using trade to ensure basic labour rights of workers in other countries are respected — fair to producers while businesses still profit." },
  { f: "Code of ethics", b: "Document explaining specifically how employees should respond in certain situations." },
  { f: "Ethical dilemma", b: "Choosing between two difficult choices, neither clearly more right or wrong. Ask: who's helped? hurt? benefits/problems? will it survive time?" },
  { f: "Whistle-blowing", b: "An employee informs officials or the public about an illegal or ethical violation." },
  { f: "Fraud", b: "A crime of lying or pretending. Types: bank, consumer, insurance, mail, pyramid scheme, telemarketer." },
  { f: "Embezzlement", b: "Accounting fraud: creating false accounts and redirecting money into them for personal gain." },
  { f: "Auditors", b: "External accountants who check and report on the validity of financial records." },
  { f: "Insider trading", b: "Buying/selling shares based on confidential information — illegal. Fines up to $1M, surrender profits, up to 2 years prison, trading ban." },
  { f: "CSR", b: "Organizations must act to serve their own interests AND society's, considering economic, environmental, and social impact of decisions." },
  { f: "The 5 CSR Principles", b: "① Safe & healthy work environment ② Fair labour policies ③ Protecting the environment ④ Truthful advertising (avoid price discrimination) ⑤ Donating to charity." },
  { f: "Duty to accommodate", b: "An employer's obligation to ensure accessibility for all employees." },
  { f: "Glass ceiling", b: "Invisible, unofficial barrier stopping women and minorities from promotions to high-level leadership jobs." },
  { f: "B Corporation", b: "For-profit business meeting high verified social/environmental standards — balances profit and purpose. Regulated by B Lab." }
]},
{ id: "fc-econ", icon: "📈", title: "Intro to Economics", cards: [
  { f: "Economics", b: "The study of human decisions in using limited resources to satisfy unlimited needs and wants for goods and services." },
  { f: "Scarcity", b: "Limited resources → limited goods/services vs unlimited wants. Forces choices, shaping consumer behaviour and business operations." },
  { f: "3 economic questions", b: "WHAT to produce? HOW to produce it? For WHOM?" },
  { f: "Command economy", b: "Government owns resources, makes ALL decisions, sets prices; limited choice, standardized goods. E.g., North Korea, Cuba." },
  { f: "Market economy", b: "Individuals/businesses decide based on supply and demand; prices set by the market; distribution by purchasing power. E.g., USA, Taiwan, New Zealand." },
  { f: "Mixed economy", b: "Government + business share decisions; essential services ensured by government; mostly market prices with some regulation. E.g., Canada, UK, France — most countries." },
  { f: "Opportunity cost", b: "The value a person could have received but passed up in pursuit of another option — the value of what's given up." },
  { f: "Natural resources", b: "From earth, water, air: soil, iron ore, gold, oil, trees, wildlife, fish, oxygen. Mostly non-renewable/limited." },
  { f: "Human resources", b: "The people who work to create goods and services (labour): farmers, teachers, nurses, factory workers." },
  { f: "Capital resources", b: "Human-made resources used to create goods/services: buildings, machinery, tools, vehicles, factories — and MONEY." },
  { f: "Specialization", b: "Each business focuses on what it does best → more efficient → relies on others → network of interdependence." }
]},
{ id: "fc-sd", icon: "⚖️", title: "Supply & Demand", cards: [
  { f: "Demand", b: "The quantity buyers are willing AND able to buy at all possible prices during a period of time." },
  { f: "Law of Demand", b: "The higher the price, the LESS consumers will demand (price ↑ → demand ↓)." },
  { f: "Supply", b: "The amount producers are willing and able to offer for sale at each possible price during a given period." },
  { f: "Law of Supply", b: "The higher the price, the MORE producers will supply (price ↑ → supply ↑)." },
  { f: "Equilibrium", b: "Price where market supply = market demand; the 'market-clearing price' — buyers and sellers are both satisfied." },
  { f: "Surplus", b: "Too much SUPPLY — sellers have more than buyers want (winter coats in spring). Sellers LOWER prices → back toward equilibrium." },
  { f: "Shortage", b: "Too much DEMAND — buyers want more than sellers have (sold-out concert). Prices RISE → back toward equilibrium." },
  { f: "Coffee Shop Game lessons", b: "Supply decisions (inventory), pricing decisions, and challenges: weather, running out of supplies, competition, customer tastes." }
]}
];

/* ===== Mock tests (mirrors the real 40-mark format) ===== */
const MOCK_TESTS = [
{
  id: "mock-a",
  title: "Mock Test A",
  intro: "Full simulation of the real Unit 1 test: 12 multiple choice, 9 matching, profit calculations, 2-of-4 short answers, and the CSR long answer. Suggested time: 50 minutes.",
  mc: [
    { q: "Leo sells custom t-shirts. He earned $500 in revenue. The blank shirts and printing supplies cost $80, and flyers cost $20. What was Leo's profit or loss?",
      choices: ["$600 profit", "$420 profit", "$400 profit", "$60 loss"], a: 2,
      explain: "Profit = Revenue − Expenses − Costs = 500 − 20 − 80 = $400 profit." },
    { q: "Which of the following is a non-profit organization?",
      choices: ["Tim Hortons", "A local food bank", "Apple", "A Subway franchise"], a: 1,
      explain: "A food bank serves a charitable purpose and reinvests everything into its mission." },
    { q: "A clothing brand has stores in Canada, the United States, and Japan. By service area, this company is…",
      choices: ["Local", "Regional", "National", "Global"], a: 3,
      explain: "Global = operates within multiple countries." },
    { q: "A business has 85 employees. By size it is classified as…",
      choices: ["Small", "Medium", "Large", "It depends on its revenue"], a: 0,
      explain: "Small = 1–99 employees." },
    { q: "Wanting food, water, and sleep belongs to which level of Maslow's hierarchy?",
      choices: ["Safety", "Physiological", "Belongingness", "Ego"], a: 1,
      explain: "Physiological needs are the base of the pyramid: water, sleep, food." },
    { q: "Joining a school club to make friends would satisfy which Maslow level?",
      choices: ["Belongingness", "Safety", "Self-actualization", "Physiological"], a: 0,
      explain: "Belongingness needs = love, friendship, acceptance." },
    { q: "Fidget spinners were extremely popular for a few months, then almost nobody wanted them. Fidget spinners were a…",
      choices: ["Trend", "Fad", "Need", "Shortage"], a: 1,
      explain: "A fad is a short-term change lasting likely less than a year. Trends last years." },
    { q: "In a limited partnership, the LIMITED partners…",
      choices: ["Run the business and have unlimited liability", "Are only responsible for the funds they invested", "Must all be family members", "Receive all the profits"], a: 1,
      explain: "Limited partners risk only what they invested (limited liability). The general partner runs the business with unlimited liability." },
    { q: "Why is the owner of a corporation NOT personally sued when the corporation is sued?",
      choices: ["Because corporations never do anything wrong", "Because the owner and the business are separate legal entities", "Because shareholders pay the damages", "Because of the partnership agreement"], a: 1,
      explain: "A corporation's legal status is distinct from the people who own or work for it — the owner is protected." },
    { q: "Regular payments of profit made to investors who own a company's stock are called…",
      choices: ["Wages", "Dividends", "Revenue", "Grants"], a: 1,
      explain: "Dividends go to shareholders — individuals who hold shares and become owners of the business." },
    { q: "Which of the following is a CROWN corporation?",
      choices: ["Apple", "IKEA", "Canada Post", "Toronto Hydro"], a: 2,
      explain: "Crown corporations are owned and funded by government, provide public service while keeping financial independence — like Canada Post and CBC." },
    { q: "Sofia works at a pharmaceutical company. Before the public announcement, she secretly sells her shares because she knows a drug trial FAILED. Sofia has committed…",
      choices: ["Embezzlement", "Consumer fraud", "Insider trading", "Whistle-blowing"], a: 2,
      explain: "Trading shares on confidential information is insider trading — punishable by fines up to $1M, surrendering profits, up to 2 years in prison, and a trading ban." }
  ],
  matching: {
    instructions: "Match each definition with the correct term. Each term is used at most once. (9 marks — 1 each)",
    terms: ["Revenue", "Expenses", "Profit", "Unlimited liability", "Shareholder", "Equilibrium", "Scarcity", "Whistle-blowing", "Co-operative", "Franchisee", "Dividend", "Trend"],
    items: [
      { def: "The money made by selling goods or services.", a: 0 },
      { def: "Payments involved in running a business and assets 'used up' operating it.", a: 1 },
      { def: "The owner is personally responsible for ALL business losses.", a: 3 },
      { def: "An individual who holds shares and becomes an owner of the business.", a: 4 },
      { def: "The price at which market supply exactly balances market demand.", a: 5 },
      { def: "Limited resources cannot meet unlimited wants, forcing choices.", a: 6 },
      { def: "An employee informs officials or the public about an illegal or ethical violation.", a: 7 },
      { def: "A business owned by its members, operating democratically — one member, one vote.", a: 8 },
      { def: "Pays fees to operate a business using an established brand's name and system.", a: 9 }
    ]
  },
  calc: [
    { marks: 2, prompt: "Leo's lemonade stand earns <b>$95</b> in revenue. The cups, lemons and sugar cost <b>$22</b>, and renting the table and sign costs <b>$8</b>. Calculate the profit or loss. (Show the formula in your explanation for full marks.)",
      solution: "Profit = Revenue − Expenses − Costs = 95 − 8 − 22 = <b>$65 profit</b>.",
      answer: 65, type: "profit" },
    { marks: 3, prompt: "You sell custom stickers at a craft fair. You sell <b>80 stickers at $2.50 each</b>. The sticker paper and ink cost <b>$95</b> (cost), and renting the booth costs <b>$45</b> (expense). <br><br>Step 1: Calculate your revenue. Step 2: Calculate the profit or loss. (1 mark: revenue · 1 mark: formula · 1 mark: correct answer)",
      solution: "Revenue = 80 × $2.50 = <b>$200</b>.<br>Profit = Revenue − Expenses − Costs = 200 − 45 − 95 = <b>$60 profit</b>.",
      answer: 60, type: "profit" }
  ],
  short: {
    instructions: "Answer <b>TWO</b> of the following four questions in complete sentences. (8 marks — 4 each)",
    questions: [
      { title: "Partnerships", prompt: "Your friend wants to become your business partner. Explain the difference between a <b>general partnership</b> and a <b>limited partnership</b>. Then give <b>one advantage</b> and <b>one disadvantage</b> of forming a partnership.",
        rubric: ["1 mark: general partnership explained — partners share gains, losses AND unlimited liability", "1 mark: limited partnership explained — general partner runs it (unlimited liability); limited partners only liable for funds invested", "1 mark: valid advantage (easy to start · shared financial burden · combined skills & expertise · profits taxed as personal income)", "1 mark: valid disadvantage (profit sharing · unlimited liability · personal conflicts · hard if a partner leaves without an agreement)"],
        model: "A general partnership is the most common form of partnership: the partners share the gains, the losses, and unlimited liability — 'what's yours is mine and what's mine is yours.' A limited partnership has a general partner who oversees and runs the business with unlimited liability, while the limited partners are only responsible for the funds they invested (limited liability). An advantage of a partnership is a shared financial burden — two people can combine money and skills, and profits are taxed as personal income rather than corporate tax. A disadvantage is profit sharing: each partner only keeps a portion of the profit, and in a general partnership each partner carries unlimited liability for the other's decisions. Partners should also sign a partnership agreement in case one wants to leave." },
      { title: "Maslow's Hierarchy of Needs", prompt: "Choose a real product you or your family use. Identify which level of <b>Maslow's hierarchy of needs</b> the product actually satisfies, and explain how its <b>advertising might appeal to a different level</b>. Use complete sentences.",
        rubric: ["1 mark: real product named + correct level identified for what it actually satisfies", "1 mark: a different level correctly named for the advertising appeal", "1 mark: explanation of HOW the ad connects to that level", "1 mark: clear, complete sentences with a specific example"],
        model: "A home security system actually satisfies a safety need, because it protects our home and gives us security and protection. However, the advertisement might show a family sleeping peacefully and use the message 'protect the people you love.' This appeals to belongingness needs — love of family — rather than safety. Companies do this because understanding which level motivates their target market helps them sell the product even when the product's real purpose is a different level of the hierarchy." },
      { title: "Trends vs Fads", prompt: "Define <b>trend</b> and <b>fad</b>, and give one example of each. Explain why a business owner needs to know the difference <b>before investing money</b> in a new product.",
        rubric: ["1 mark: trend defined — general direction/change in society that lasts a long time (years)", "1 mark: fad defined — temporary, short-term change, likely less than a year", "1 mark: valid examples of each (trend: online shopping, AI · fad: fidget spinners, squishies)", "1 mark: explanation — investing in a fad risks stuck inventory when the craze dies; trends support longer-term business decisions"],
        model: "A trend is a general direction or change in society that lasts a long time — for years — like online shopping or AI in business. A fad is a change that leads to only a temporary, short-term adjustment, likely less than a year, like fidget spinners or squishies. A business owner must tell them apart because investing in a fad is risky: when the fad dies, the business is left with inventory nobody wants, like a store full of fidget spinners. A trend, on the other hand, shows lasting demand — businesses that moved online early grew with their customers for years. For example, in the 1970s the trend of women entering the workforce created lasting demand for convenience food, extended shopping hours, and household appliances." },
      { title: "Opportunity Cost", prompt: "You have $60 and you choose to buy <b>concert tickets</b> instead of a new video game or dinner out with friends. Define <b>opportunity cost</b>, then identify the opportunity cost of your choice and explain your reasoning.",
        rubric: ["1 mark: opportunity cost defined — the value a person could have received but passed up in pursuit of another option (value of what's given up)", "1 mark: identifies the specific alternative(s) given up (video game and/or dinner)", "1 mark: explains that the next-best option's value is the opportunity cost", "1 mark: clear explanation using the $60/limited budget situation"],
        model: "Opportunity cost is the value a person could have received but passed up in pursuit of another option — in other words, the value of what you give up. Because of scarcity, my $60 can only buy one thing. By choosing the concert tickets, I give up the video game and the dinner with friends. The opportunity cost is the value of the next-best option, the video game, because that is what I would most likely have bought instead. Recognizing opportunity cost helps me decide whether the concert is really worth more to me than the alternatives." }
    ]
  },
  csr: {
    scenario: "You have just been hired as the new CEO of <b>SnackCo</b>, a snack-food company. Since you arrived you have discovered: <br>① workers say the factory machines are unsafe and they are afraid to report injuries; <br>② the hiring manager rejects qualified applicants who are over 50 and refuses to accommodate a wheelchair user; <br>③ the factory dumps waste oil into the river behind the plant; <br>④ SnackCo's newest ads claim its chips 'cure hunger for hours!' — which is untrue; <br>⑤ SnackCo has never supported any community or charity programs.<br><br>The Board of Directors asks you for a CSR plan.",
    prompt: "Identify the <b>FIVE CSR principles</b> and explain <b>one specific action</b> SnackCo should take for each one to fix the problems above. For each principle: name it, give the specific action, and explain why/how it helps. (6 marks)",
    rubric: ["1 mark per principle: named correctly AND matched to a specific action for the scenario (5 principles × 1 = 5 marks)", "1 mark: overall explanation quality — explains why/how actions help workers, society, the environment, or the company"],
    model: "SnackCo should apply the five CSR principles. ① Safe and healthy work environment: repair and upgrade the factory machines, train workers on safety, and create a no-punishment process for reporting injuries — employees have the right to refuse unsafe work and to know about hazards, and safer workers mean fewer accidents and less downtime. ② Fair labour policies: end age discrimination in hiring and follow the duty to accommodate by making the workplace accessible for the wheelchair user — this ensures equal opportunity and builds a skilled, loyal workforce. ③ Protecting the environment: stop dumping waste oil in the river and install proper disposal or recycling, like IKEA's move to fully circular operations — this prevents environmental harm and protects the brand from fines and backlash. ④ Truthful advertising: correct the 'cures hunger' ads, like Dove's commitment to truthful portrayals — honest ads keep customer trust and avoid consumer-fraud complaints. ⑤ Donating to charity: start a community program, like Microsoft's employee-matching gifts — giving back strengthens the community and the company's reputation, showing SnackCo serves society's interests, not just profit."
  }
},
{
  id: "mock-b",
  title: "Mock Test B",
  intro: "A second full simulation with fresh questions — same real format: 12 MC, 9 matching, calculations, 2-of-4 short answers, CSR long answer. Suggested time: 50 minutes.",
  mc: [
    { q: "The money made by selling goods or services is called…",
      choices: ["Profit", "Revenue", "Expenses", "Dividends"], a: 1,
      explain: "Revenue = money from selling. Profit = what's left after expenses and costs." },
    { q: "A dentist cleaning your teeth is an example of a…",
      choices: ["Good", "Service", "Natural resource", "Non-profit"], a: 1,
      explain: "A service is assistance provided; a good is an item you can see or touch." },
    { q: "Sarah runs a housekeeping business alone, funded from her own savings, and she is personally responsible for all its debts. Her business is a…",
      choices: ["Corporation", "Co-operative", "Sole proprietorship", "Franchise"], a: 2,
      explain: "One owner, personally responsible for losses = sole proprietorship with unlimited liability (e.g., housekeeping service)." },
    { q: "In a general partnership…",
      choices: ["Only the general partner shares profits", "Partners share gains, losses and unlimited liability", "Partners have limited liability", "Shareholders elect the board"], a: 1,
      explain: "General partnership: 'what's yours is mine and what's mine is yours' — shared gains, losses, unlimited liability." },
    { q: "The board of directors of a public corporation is elected by…",
      choices: ["The CEO", "The employees", "The shareholders", "The customers"], a: 2,
      explain: "Shareholders elect the board to set strategy and oversee management — the board can even fire the CEO." },
    { q: "Which of these is a PRIVATE corporation?",
      choices: ["Apple", "Lego", "Canada Post", "The TTC"], a: 1,
      explain: "Private corporations are owned by a small group and their shares are NOT publicly traded — like IKEA and Lego. Apple is public; Canada Post is Crown; TTC is municipal." },
    { q: "One major challenge of buying a franchise is…",
      choices: ["You must invent your own logo and menu", "Strict rules and very limited freedom to make changes", "You keep none of the profits", "Unlimited liability for the whole brand's debts"], a: 1,
      explain: "Franchisees face limited freedom, strict consistency rules, franchise competition, brand-reputation risk, and high investment fees." },
    { q: "In a co-operative, decisions are made…",
      choices: ["By the founder only", "Democratically — one member, one vote", "By shareholders based on shares owned", "By the government"], a: 1,
      explain: "Co-ops are owned by members who share decision-making — one member = one vote, focused on member needs, not max profit." },
    { q: "Jordan has $30 and buys a pizza instead of going to a movie. The movie he gave up is his…",
      choices: ["Expense", "Revenue", "Opportunity cost", "Surplus"], a: 2,
      explain: "Opportunity cost = the value of what you give up when you choose one option over another." },
    { q: "Canada, where government ensures essential services but most prices are market-driven, is an example of a…",
      choices: ["Command economy", "Pure market economy", "Mixed economy", "Traditional economy"], a: 2,
      explain: "Mixed economies share decision-making between government and business — most countries today, including Canada, the UK, and France." },
    { q: "A store is overstocked with winter coats in spring and starts lowering prices. The store is experiencing a…",
      choices: ["Shortage", "Surplus", "Equilibrium", "Fad"], a: 1,
      explain: "Surplus = too much supply. Sellers lower prices to attract buyers, pushing the market back toward equilibrium." },
    { q: "According to the law of demand, if the price of a product rises…",
      choices: ["Consumers will demand less of it", "Consumers will demand more of it", "Producers will supply less of it", "Demand is unaffected"], a: 0,
      explain: "Law of demand: higher price → less demand. (Law of supply: higher price → more supply.)" }
  ],
  matching: {
    instructions: "Match each definition with the correct term. Each term is used at most once. (9 marks — 1 each)",
    terms: ["Profit", "Non-profit organization", "Sole proprietorship", "Corporation", "Limited liability", "Opportunity cost", "Demand", "Supply", "Fad", "Partnership agreement", "Scarcity", "Goods"],
    items: [
      { def: "The income left after all costs and expenses are paid.", a: 0 },
      { def: "An organization serving a social or charitable purpose that reinvests any profit into its mission.", a: 1 },
      { def: "A business owned and run by one person who is responsible for all its losses.", a: 2 },
      { def: "A business with legal status distinct from the people who own or work for it.", a: 3 },
      { def: "Being responsible only for the money you invested in a business.", a: 4 },
      { def: "The value of the next-best option you give up when making a choice.", a: 5 },
      { def: "The quantity of a good or service that buyers are willing and able to buy at possible prices.", a: 6 },
      { def: "The amount producers are willing and able to offer for sale at each possible price.", a: 7 },
      { def: "A short-lived product craze, likely lasting less than a year.", a: 8 }
    ]
  },
  calc: [
    { marks: 2, prompt: "Sofia runs a weekend car wash. She earned <b>$320</b> in revenue. Soap and wax supplies cost <b>$45</b>, renting the pressure washer costs <b>$60</b>, and she paid her friend <b>$100</b> in wages. Calculate the profit or loss.",
      solution: "Profit = Revenue − Expenses − Costs = 320 − (45 + 60 + 100) = 320 − 205 = <b>$115 profit</b>.",
      answer: 115, type: "profit" },
    { marks: 3, prompt: "Ben sells custom hoodies at the school fair. He sells <b>20 hoodies at $13 each</b>. The hoodies and printing cost <b>$150</b> (cost), renting the table costs <b>$80</b>, and flyers cost <b>$45</b> (expenses). <br><br>Step 1: Calculate his revenue. Step 2: Calculate the profit or <i>loss</i>. Careful — check your numbers! (1 mark: revenue · 1 mark: formula · 1 mark: correct answer)",
      solution: "Revenue = 20 × $13 = <b>$260</b>.<br>Profit = 260 − (80 + 45) − 150 = 260 − 275 = <b>−$15</b> → a LOSS of $15.",
      answer: 15, type: "loss" }
  ],
  short: {
    instructions: "Answer <b>TWO</b> of the following four questions in complete sentences. (8 marks — 4 each)",
    questions: [
      { title: "Partnership Agreements", prompt: "List <b>TWO things</b> business partners should negotiate or decide <b>before</b> signing a partnership agreement, and explain <b>why the agreement matters</b> if a partner later wants to leave the business.",
        rubric: ["2 marks: two valid items — responsibilities · decision making · ownership split (50/50, 40/60) · scheduling · financial investment · profit splits · goals · values · what if a partner leaves", "2 marks: explains the agreement protects everyone — without one, a partner leaving may be difficult (disputes over money, ownership, responsibilities)"],
        model: "Before signing a partnership agreement, partners should negotiate things like how ownership is split (50/50 or 40/60), who is responsible for which tasks, how much money each person invests, how profits will be divided, and what happens if one partner wants to leave. The agreement matters because if a partner wants to leave and there is no agreement in place, it can be very difficult — the remaining partner might lose access to the business's money, and there could be arguments over responsibilities, values, and profit splits. The written agreement protects both partners because everyone agreed to the terms from the start." },
      { title: "Maslow's Hierarchy", prompt: "Name <b>all five levels</b> of Maslow's hierarchy of needs in order (bottom to top), and explain how <b>one product</b> could satisfy needs at <b>two different levels</b> for two different consumers.",
        rubric: ["2 marks: all five levels in order — physiological, safety, belongingness, ego, self-actualization (1 mark if listed but out of order or incomplete)", "1 mark: one product connected to a correct level", "1 mark: explains how the same product meets a different level for another consumer (e.g., a phone: belongingness for chatting with friends, ego/uniqueness for the latest model)"],
        model: "Maslow's five levels from bottom to top are: physiological (water, sleep, food), safety (shelter, security, protection), belongingness (love, friendship, acceptance), ego (self-esteem, achievement, uniqueness, independence), and self-actualization (realizing your full potential). A smartphone is a good example of a product that can satisfy two different levels: for one teenager, the phone satisfies belongingness needs because it is how they stay connected with friends; for another consumer, buying the newest model satisfies ego needs because it makes them feel unique and successful. Businesses study the hierarchy to understand their target market and which level actually motivates each group." },
      { title: "Trends: the 1970s case", prompt: "In the 1970s, a major <b>trend</b> began: more women entering the workforce. Identify <b>TWO products or services</b> businesses introduced in response to this trend, and explain how a <b>trend is different from a fad</b> using this example.",
        rubric: ["2 marks: two valid responses — convenience food · extended shopping and banking hours · convenient household appliances · hotels including hair dryers and ironing boards", "1 mark: trend lasts years / long-term change in society; fad is temporary, less than a year", "1 mark: connects the difference to the example — the workforce change created lasting demand, unlike a short craze"],
        model: "The 1970s trend of more women entering the workforce created demand for convenience food, extended shopping and banking hours, convenient household appliances, and hotels including hair dryers and ironing boards. A trend is a general direction in society that lasts a long time — years — while a fad is a temporary, short-term change, likely less than a year. The women-in-the-workforce example shows a real trend: the change in society was permanent, so the new consumer needs lasted for decades and businesses could invest confidently — unlike fidget spinners, where demand disappeared within a year." },
      { title: "Scarcity & Opportunity Cost", prompt: "Define <b>scarcity</b> and <b>opportunity cost</b>, and explain how scarcity forces <b>both businesses and consumers</b> to make choices. Use an example.",
        rubric: ["1 mark: scarcity defined — limited resources to produce limited goods/services vs unlimited wants", "1 mark: opportunity cost defined — the value of what is given up when choosing an option", "1 mark: explains the connection — scarcity forces choices; every choice has an opportunity cost", "1 mark: example involving businesses AND/OR consumers (e.g., the $50 dilemma, a business choosing how to use limited money)"],
        model: "Scarcity means there are only limited resources to produce a limited amount of goods and services, while human wants are unlimited. Because of scarcity, we must make choices about how to use what we have. Opportunity cost is the value a person could have received but passed up — the value of what's given up when we choose. Scarcity forces consumers to choose: with $50, buying gaming accessories means giving up the concert (the opportunity cost). It forces businesses to choose too: a company with limited money must decide whether to spend it on new machines or advertising, and choosing the machines means giving up the benefits of the ads. Every choice — by people and businesses — has an opportunity cost because of scarcity." }
    ]
  },
  csr: {
    scenario: "You are on the leadership team of <b>TechTrend</b>, a company that makes phone cases. Next year TechTrend plans to open a factory overseas where labour is cheap and laws are weak, and to launch a huge advertising campaign. Some managers argue: 'Just make money — CSR is a distraction.' The Board disagrees and asks you to prove them wrong.",
    prompt: "Explain how TechTrend should apply <b>EACH of the five CSR principles</b> as it opens the new factory and runs the ad campaign. For each principle: name it, give a specific action, and explain why/how it benefits workers, society, the environment, or the company. (6 marks)",
    rubric: ["1 mark per principle: named correctly AND applied to the overseas factory / ad campaign scenario (5 × 1 = 5 marks)", "1 mark: overall explanation quality — reasons and/or examples (fair trade, IKEA/Dove/Microsoft examples, B Corp idea)"],
    model: "TechTrend should apply all five CSR principles as it expands. ① Safe and healthy work environment: train and equip the overseas factory workers properly and audit machine safety, because workers everywhere deserve safety — and safe factories avoid costly accidents. ② Fair labour policies: pay fair wages, follow work-hour laws, hire without discrimination, and follow fair trade principles so workers' basic labour rights in the other country are respected — this avoids sweatshop scandals that destroy brands. ③ Protecting the environment: use recycled materials in the cases and cut packaging waste, like IKEA's circular-business goal and Dove's recyclable-packaging commitment — protecting the environment also attracts eco-friendly customers. ④ Truthful advertising: run the campaign honestly — no exaggerated claims and no altered images, like Dove's no-airbrushing pledge — because truthful ads build long-term trust. ⑤ Donating to charity: donate devices or funds to schools in the new community, like Microsoft Philanthropies — giving back shows TechTrend serves society's interests, not just profit. CSR is not a distraction: it protects the company's reputation, attracts customers and investors, and balances profit with purpose."
  }
}
];
